apiVersion: v1
kind: Service
metadata:
  name: {{ include "monero.fullname" . }}
  labels:
    {{- include "monero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rpc }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.rpcrestricted }}
      targetPort: rpcrestricted
      protocol: TCP
      name: rpcrestricted
    {{- if  .Values.config.zmq }}
    - port: {{ .Values.service.zmq }}
      targetPort: zmq
      protocol: TCP
      name: zmq
    - port: {{ .Values.service.zmqpub }}
      targetPort: zmqpub
      protocol: TCP
      name: zmqpub
    {{- end }}
  selector:
    {{- include "monero.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }} 
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  {{- end }}

---

{{ if ne .Values.serviceP2P.type "hostPort" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monero.fullname" . }}-p2p
  labels:
    {{- include "monero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceP2P.type }}
  ports:
    - port: {{ .Values.serviceP2P.p2p }}
      targetPort: p2p 
      protocol: TCP
      name: p2p
      nodePort: {{ .Values.serviceP2P.p2p }}
  selector:
    {{- include "monero.selectorLabels" . | nindent 4 }}
{{ end }}
