apiVersion: v1
kind: Service
metadata:
  name: {{ include "monero.fullname" . }}
  labels: {{ include "monero.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.service.type }}
  ports:
    {{ if eq .Values.monero.testnet true}}
    - port: {{ .Values.service.testnetRpcPort }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.testnetP2pPort }}
      protocol: TCP
      name: p2p
    {{ else if eq .Values.monero.stagenet true }}
    - port: {{ .Values.service.stagenetRpcPort }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.stagenetP2pPort }}
      protocol: TCP
      name: p2p
    {{ else }}
    - port: {{ .Values.service.rpcPort }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: p2p
    {{ end }}
  selector: {{ include "monero.selectorLabels" . | nindent 4 }}
